CREATE TABLE ARTIFACT
(
  GROUP_ID varchar(256) NOT NULL,
  ARTIFACT_ID varchar(256) NOT NULL,
  VERSION varchar(256) NOT NULL,
  TYPE varchar(10) NOT NULL,
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL
);


CREATE INDEX idx_artifact on artifact (GROUP_ID, _, version, type);

CREATE TABLE BUILD
(
  JOB_FULL_NAME varchar(512) NOT NULL,
  BUILD_NUMBER integer NOT NULL,
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE INDEX idx_build on BUILD (JOB_FULL_NAME, BUILD_NUMBER);


CREATE TABLE DEPENDENCY
(
  ARTIFACT_ID integer NOT NULL,
  BUILD_ID integer NOT NULL,
  SCOPE varchar(20),
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CONSTRAINT DEPENDENCY_BUILD_ID_FK FOREIGN KEY (BUILD_ID) REFERENCES BUILD (ID) ON DELETE CASCADE,
  CONSTRAINT DEPENDENCY_ARTIFACT_ID_FK FOREIGN KEY (ARTIFACT_ID) REFERENCES ARTIFACT(ID) ON DELETE CASCADE
);

CREATE TABLE GENERATED
(
  ARTIFACT_ID INT NOT NULL,
  BUILD_ID INT NOT NULL,
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CONSTRAINT GENERATED_BUILD_ID_FK FOREIGN KEY (BUILD_ID) REFERENCES BUILD (ID) ON DELETE CASCADE,
  CONSTRAINT GENERATED_ARTIFACT_ID_FK FOREIGN KEY (ARTIFACT_ID) REFERENCES ARTIFACT (ID) ON DELETE CASCADE
);


CREATE TABLE VERSION
(
  VERSION integer
);

INSERT INTO VERSION(VERSION) SET "1";





