ALTER TABLE JENKINS_JOB MODIFY JENKINS_MASTER_ID INT NOT NULL;

DROP INDEX IDX_JENKINS_JOB ON JENKINS_JOB;

CREATE UNIQUE INDEX IDX_JENKINS_JOB on JENKINS_JOB (JENKINS_MASTER_ID, FULL_NAME);

UPDATE VERSION SET VERSION = 9;
