FROM localhost/pipeline-maven/sshd

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        software-properties-common \
        openjdk-17-jdk-headless \
        curl \
        ant \
        git

