CREATE TABLE MAVEN_PARENT_PROJECT
(
  ARTIFACT_ID integer NOT NULL,
  BUILD_ID integer NOT NULL,
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IGNORE_UPSTREAM_TRIGGERS BOOLEAN DEFAULT FALSE,
  CONSTRAINT PARENT_PROJECT_BUILD_ID_FK FOREIGN KEY (BUILD_ID) REFERENCES JENKINS_BUILD (ID) ON DELETE CASCADE,
  CONSTRAINT PARENT_PROJECT_ARTIFACT_ID_FK FOREIGN KEY (ARTIFACT_ID) REFERENCES MAVEN_ARTIFACT(ID) ON DELETE CASCADE
);


UPDATE VERSION SET VERSION = 5;






