ALTER TABLE GENERATED_MAVEN_ARTIFACT ADD REPOSITORY_URL varchar(256) DEFAULT NULL;

ALTER TABLE GENERATED_MAVEN_ARTIFACT ADD EXTENSION varchar(256) DEFAULT NULL;

ALTER TABLE MAVEN_ARTIFACT ADD CLASSIFIER varchar(256) DEFAULT NULL;

UPDATE VERSION SET VERSION = 6;






