CREATE TABLE JENKINS_MASTER
(
  LEGACY_INSTANCE_ID varchar(256) NOT NULL,
  URL varchar(256) NOT NULL,
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL
);
CREATE UNIQUE INDEX IDX_LEGACY_INSTANCE_ID on JENKINS_MASTER (LEGACY_INSTANCE_ID);

ALTER TABLE JENKINS_JOB ADD COLUMN JENKINS_MASTER_ID integer;

UPDATE VERSION SET VERSION = 8;
