CREATE TABLE JENKINS_BUILD_UPSTREAM_CAUSE
(
  UPSTREAM_BUILD_ID integer NOT NULL,
  DOWNSTREAM_BUILD_ID integer NOT NULL,
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CONSTRAINT UPSTREAM_BUILD_ID_FK FOREIGN KEY (UPSTREAM_BUILD_ID) REFERENCES JENKINS_BUILD (ID) ON DELETE CASCADE,
  CONSTRAINT DOWNSTREAM_BUILD_ID_FK FOREIGN KEY (DOWNSTREAM_BUILD_ID) REFERENCES JENKINS_BUILD (ID) ON DELETE CASCADE
);

UPDATE VERSION SET VERSION = 11;

